package main

import (
	"fmt"
	"log"
	"net/http"
	_ "net/http/pprof" // 引入 pprof 模块，排查内存泄漏
	"os"

	"ccian.cc/really/arweave-api/api"
	// _ "ccian.cc/really/arweave-api/docs" // docs is generated by Swag CLI, you have to import it.

	// _ "github.com/mkevac/debugcharts"       // 可选，添加后可以查看几个实时图表数据
	"gopkg.in/urfave/cli.v1"
)

// @title really arweave API
// @version 1.0.0
// @description This is an API server for really arweave chain. Use OpenAPI 2.0 specification.
//
// @contact.name BillZong
// @contact.email billzong@163.com
//
// @BasePath /api/v1
func main() {
	if os.Getenv("debugPProf") == "true" {
		go func() {
			// terminal: $ go tool pprof -http=:8081 http://localhost:6060/debug/pprof/heap
			// web:
			// 1、http://localhost:8081/ui
			// 2、http://localhost:6060/debug/charts
			// 3、http://localhost:6060/debug/pprof
			log.Println(http.ListenAndServe("0.0.0.0:6060", nil))
		}()
	}

	app := cli.NewApp()

	app.Name = "Really arweave API Server"
	app.Version = "1.0.0"
	app.Description = "API server for really arweave chain"
	app.Flags = []cli.Flag{
		cli.StringFlag{
			Name:  "config,c",
			Usage: "config file",
			Value: "./config/config.yaml",
		},
	}
	server := api.NewServer()
	app.Action = server.Start

	err := app.Run(os.Args)
	if err != nil {
		fmt.Println(err)
	}}
